export type RootStackParamList = {
  AppLoading: undefined;
  Start: undefined;
  Login: undefined;
  VerifyOTP: { phoneNumber: string; countryCode: string; callingCode: string; isRegistering: boolean };
  Register: undefined;
  Home: undefined;
  CoreProfile: undefined;
  RegisterCoreProfile: undefined;
  RegisterPhysicalInfo: undefined;
  RegisterLocation: undefined;
  RegisterPreferences: undefined;
  RegisterSchedule: { activities?: string[] };
  RegisterPreferredDays: { activities?: string[] };
  RegisterGoals: undefined;
  RegisterGetStronger: undefined;
  RegisterGetStrongerDetails: undefined;
  RegisterGetFaster: undefined;
  RegisterGetFasterDetails: { goalType: 'sprint' | 'long-distance' | 'both' };
  RegisterGainMuscle: undefined;
  RegisterGainMuscleDetails: undefined;
  RegisterLoseBodyFat: undefined;
  RegisterLoseBodyFatDetails: undefined;
  RegisterTrainEvent: undefined;
  RegisterTrainEventDetails: { eventType: string };
  RegisterTrainEventTrainingStatus: { eventType: string; eventMonth: string; eventYear: number };
  RegisterTrainEventCurrentStatus: { eventType: string; eventMonth: string; eventYear: number };
  RegisterPushMyself: undefined;
  RegisterSummaryReview: undefined;
  Weightlifting: undefined;
  WeightliftingEquipment: undefined;
  WeightliftingMaxes: undefined;
  Swimming: undefined;
  SwimmingStyle: undefined;
  SwimmingExample: undefined;
  Pilates: undefined;
  PilatesStudio: undefined;
  Yoga: undefined;
  YogaStudio: undefined;
  Running: undefined;
  RunningStyle: undefined;
  RunningExample: undefined;
  RunningDistance: undefined;
  Sports: undefined;
  SportsType: undefined;
  Walking: undefined;
  WalkingDistance: undefined;
  Other: undefined;
  AnythingElse: undefined;
};

